# Generated by Django 5.1.4 on 2026-08-30 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_activityevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('overdue_after_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('allow_custom', models.BooleanField(default=True)),
                ('pair_group', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'task categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='kind',
            field=models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged'), ('ordered', 'Ordered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.CreateModel(
            name='TaskOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_custom', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='board.taskcategory')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='board.patient')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='board.taskcategory')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.taskoption')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ticked', models.BooleanField(default=False)),
                ('ticked_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_states', to='board.patient')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.taskcategory')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('patient', 'category'), name='unique_slotstate')],
            },
        ),
        migrations.AddConstraint(
            model_name='taskoption',
            constraint=models.UniqueConstraint(fields=('category', 'label'), name='unique_option_per_category'),
        ),
    ]
