# Generated by Django 5.1.4 on 2026-08-30 20:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_taskcategory_alter_activityevent_kind_taskoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='kind',
            field=models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged'), ('ordered', 'Ordered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('note', 'Note'), ('vitals', 'Vitals')], max_length=20),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author_name', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='board.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('pulse', models.PositiveIntegerField(blank=True, null=True)),
                ('temp_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('resp_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('spo2', models.PositiveIntegerField(blank=True, null=True)),
                ('rbs', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='board.patient')),
            ],
            options={
                'verbose_name_plural': 'vitals entries',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
