# Generated by Django 5.1.4 on 2026-08-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_activityevent_kind_note_vitalsentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlotState',
        ),
    ]
