# Generated by Django 5.1.4 on 2026-08-31 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_delete_slotstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='kind',
            field=models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged'), ('ordered', 'Ordered'), ('completed', 'Completed'), ('reopened', 'Reopened'), ('edited', 'Edited'), ('cancelled', 'Cancelled'), ('note', 'Note'), ('vitals', 'Vitals'), ('cleared_all', 'Data cleared')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('bed__isnull', False), ('status', 'active')), fields=('bed',), name='one_active_patient_per_bed'),
        ),
    ]
